mysql:
  hostport: 127.0.0.1:3306
  username: root
  password: xuelei123
  database: kv
  poolsize: 20
  idlesize: 10
  max_life_time: 10

redis:
  hostport: 127.0.0.1:6379
  auth:
  timeout: 5
  poolsize: 

kafka:
  hostports: 127.0.0.1:9092
  concurrent: 3
  enable: true
